# Generated by Django 6.0.5 on 2026-05-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id_estacionamiento', models.AutoField(primary_key=True, serialize=False)),
                ('numero_espacio', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobros.estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobros.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobros.vehiculo'),
        ),
    ]
